[TCP]
server = giggahash.com
port = 14533
password = tu8tu5

[SQL]
host = 127.0.0.1
database = yaamp
username = yaamp
password = teamrsi123teamrsi123teamrsi123

[STRATUM]
algo = lyra2v2
difficulty = 1
max_ttf = 40000
reconnect = 1
logdir = /tmp/

[DEBUGLOG]
client = 1
