[TCP]
server = giggahash.com
port = 12478
password = tu8tu5

[SQL]
host = 127.0.0.1
database = yaamp
username = yaamp
password = teamrsi123teamrsi123teamrsi123

[WALLETS]
include = SPSC

[STRATUM]
algo = spacescrypt
difficulty = 128
max_ttf = 40000
reconnect = 1
logdir = /tmp/

[DEBUGLOG]
client = 1
