[TCP]
server = giggahash.com
port = 17334
password = tu8tu5

[SQL]
host = 127.0.0.1
database = yaamp
username = root
password = teamrsi123teamrsi123teamrsi123

[WALLETS]
BRICS = Br1csC0inRpcJ5k9mNv2

[STRATUM]
algo = sha256
difficulty = 256
max_ttf = 40000
reconnect = 1
logdir = /tmp/
