[TCP]
server = giggahash.com
port = 17335
password = tu8tu5

[SQL]
host = 127.0.0.1
database = yaamp
username = root
password = teamrsi123teamrsi123teamrsi123

[WALLETS]
QNTM = Qn7mT0k3nRpcW8x3pLv1

[STRATUM]
algo = scrypt
difficulty = 256
max_ttf = 40000
reconnect = 1
logdir = /tmp/
