[TCP]
server = giggahash.com
port = 17333
password = tu8tu5

[SQL]
host = 127.0.0.1
database = yaamp
username = root
password = teamrsi123teamrsi123teamrsi123

[WALLETS]
SILVR = S1lv3rRpcK9x2mNq8

[STRATUM]
algo = sha256d
difficulty = 256
max_ttf = 40000
reconnect = 1
logdir = /tmp/
